language: node_js
os:
  - linux
dist: xenial
node_js:
  - node
services:
  - xvfb
script: xvfb-run --auto-servernum --server-num=1 --server-args="-screen 1 1024x768x24" make test
cache:
  directories:
    - node_modules
branches:
  only:
    - master
